# Generated by Django 3.2.14 on 2022-08-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_full'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='full',
            new_name='full_content',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=250),
        ),
    ]
